name: Update Understat data (weekly)

on:
  schedule:
    # Runs Monday at 06:15 UTC (cron is UTC)
    - cron: "15 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure the newest understat package on every run
          pip install --upgrade understat

      - name: Run updater
        run: |
          python scripts/fetch_player_data.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/understat_players

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Update Understat data"
            git push
          fi